from tkinter import *
from PIL import Image, ImageTk
from tkinter import ttk
def insert(string, root, list, bg):
  Label(root, text=string, bg=bg, fg='White').place(relx=0.075, rely=0.05)
  for item in list:
    item.destroy()
  Button(root, text="Continue", bg=bg, command= lambda: root.destroy()).pack()
def Questionaire(root, order, answers, bg, Question):
  subroot = Toplevel(root)
  subroot.configure(bg=bg)
  subroot.config(width=200, height=200, cursor='star')
  subroot.title("Question")
  subroot.maxsize(2000,2000)
  subroot.minsize(200,200)
  subroot.geometry("500x500")
  ico = Image.open('test.jpg')
  photo = ImageTk.PhotoImage(ico)
  subroot.wm_iconphoto(False, photo)
  Label(subroot, text=Question, bg=bg, fg="White").pack()
  b1 = Button(subroot, text=answers[0], command=lambda: insert(order[0], subroot, List, bg))
  b1.pack()
  b2 = Button(subroot, text=answers[1], command=lambda: insert(order[1], subroot, List, bg))
  b2.pack()
  b3 = Button(subroot, text=answers[2], command=lambda: insert(order[2], subroot, List, bg))
  b3.pack()
  b4 = Button(subroot, text=answers[3], command=lambda: insert(order[3], subroot, List, bg))
  b4.pack()
  List = [b1,b2,b3,b4]
def layer(images, texts, command, bg, fg, intro_text, orders, answers, title, Questions):
    global root
    root.destroy()
    root = Tk()
    root.state('zoomed')
    root.configure(bg=bg)
    root.title(title)
    ico = Image.open('test.jpg')
    photo = ImageTk.PhotoImage(ico)
    root.wm_iconphoto(False, photo)

    # Main Frame + Canvas + Scrollbar
    frame = Frame(root, bg=bg)
    frame.pack(fill=BOTH, expand=True)

    canvas = Canvas(frame, bg=bg, bd=0, highlightthickness=0)
    scrollbar = ttk.Scrollbar(frame, orient=VERTICAL, command=canvas.yview)
    canvas.configure(yscrollcommand=scrollbar.set)

    scrollbar.pack(side=RIGHT, fill=Y)
    canvas.pack(fill=BOTH, expand=True)

    # Content Frame inside Canvas
    content = Frame(canvas, bg=bg)
    canvas.create_window((0, 0), window=content, anchor=NW)

    def update_scrollregion(event):
        canvas.configure(scrollregion=canvas.bbox("all"))
    content.bind("<Configure>", update_scrollregion)

    # Content starts here
    Message(content, text=intro_text, width=800, bg=bg, fg=fg, font=('Public Sans', 20)).pack(pady=10)
    image_ref = []
    button_ref = []
    for i in range(len(images)):
    # Load images
      image = Image.open(images[i])
      image = image.resize((image.width // 2, image.height // 2))
      img_tk = ImageTk.PhotoImage(image)
      image_ref.append(img_tk)
      button = Button(content, image=img_tk, padx=1, pady=1, command=lambda i=i:Questionaire(root, orders[i], answers[i], bg, Question=Questions[i]))
      button_ref.append(button)
      button.pack(pady=10)
      Message(content, bg=bg, fg=fg, width=800, text=texts[i]).pack(pady=10)
    Button(content, text="Descend deeper", bg=bg, fg=fg, command=command).pack()
    root.mainloop()

root = Tk()
root.state('zoomed')
root.configure(bg='#300900')
root.title("Hell")
root.maxsize(2000,2000)
root.minsize(500,500)
root.geometry("500x500")
ico = Image.open('test.jpg')
photo = ImageTk.PhotoImage(ico)
root.wm_iconphoto(False, photo)
canvas = Canvas(root, bg="#300900", width=500, height=500, bd=0, cursor="circle")
canvas.pack(fill=BOTH, expand=True)
Label(canvas, text="Welcome to the world of Dante's Inferno" ,bg='#300900', fg='#9a1d00', font=('Terminal', 50)).pack()
Label(canvas, text="\n \n \n \n \n \n \n \n",bg='#300900', fg='#9a1d00').pack()
Button(canvas, text="Join the souls of the damned", bg='#300900', fg='#9a1d00' ,font=('Symbol', 15), command=lambda: layer(["Dante.jpg", "Virgil.jpg"], ["At this stage, Dante is a lost soul, almost questioning his faith in God, his entire journey begin essentially to show him the fate of all, and to renew his faith in God. He is no saint, he is a human like anyone else, reacting as how most would to seeing the fates of sinners.", "Virgil is a dead poet, who acts as Dante's guide to Hell, here he symbolises human wisdom and knowledge, and he was just as big of an influence in reality as he is in the story. He claims to have been around in Rome in the time of Augustus, when 'All the Gods were lying cheats' (translated of course)."], title="Surface", bg="#300900", fg='#9a1d00', intro_text="Of course, the story does not begin in Hell, Dante was on the surface at first of course, in fact he doesn't enter Hell until the 3rd canto, it simply begins with Dante in a dark forest, encountering a leopard, but Virgil is also introduced in this first canto, and he explains what this beast was, in the 2nd canto Virgil essentially explains to Dante how Beatrice chose Virgil as a guide (Beatrice was Dante's first love), we do not meet Beatrice herself until 'Purgatorio' where she becomes the guide.", orders=[["Incorrect", "Incorrect", "Correct", "Incorrect"], ["Correct", "Incorrect", "Incorrect", "Incorrect"]], answers=(["A family member", "His wife", "His first love (although unreturned)", "His first girlfriend"], ["Augustus", "Caesar", "Caligula", "Nero"]), Questions= ["Who was Beatrice to Dante?","Virgil lived in the time of which roman emperor?"],
                                                                                                                          command=lambda: layer(["Gate.jpg", "apathy.jpg"], ["Abandon all hope, ye who enter here.", "Everyone in the threshold is intentionally anonymous, however it is known that the angels who chose to side with Lucifer were thrown out of heaven to here. This is the place dedicated to all those that never chose a morality. Apathy is no excuse from damnation. To pass into Hell you must pass the river Acheron"], title="The Threshold", bg="#300900", fg='#9a1d00', intro_text="Just remember... you did this to yourself, Welcome to the threshold of Hell, here you'll find the apathetic. Charon (from greek myth) is also here, he will be the one to bring you truly to Hell.", orders=[["Correct", "Incorrect", "Incorrect", "Incorrect"], ["Incorrect", "Correct", "Incorrect", "Incorrect"]], answers=[["Abandon all hope, ye who enter here.", "Abandon all hope.", "Welcome to Hell", "There is no inscription"], ["Charon", "Fallen Angels", "The unbaptised", "Believers who weren't morally great"]], Questions=["What is the inscription at the gate of Hell?", "Who is among those damned in this layer?"], 
                                                                                                                           command=lambda: layer(["1_2.jpg", "1.jpg"], ["It begins simply with Dante meeting many famous poets, all of which are known for their own individual famous works (e.g. Homer's the Illiad and the Odyssey)", "There is described to be a castle, with 7 gates to enter, upon passing through there was a green meadow, where he met many mythological figures and some historical figures, after which he met some philosphers (The other 4 poets followed Dante and Virgil here), after meeting more people he moves on to the next circle of Hell"], bg="#251317", fg='#FFFFFF', intro_text="This is Limbo, the first circle of Hell, here you will find pagans and the unbaptized. This is where Virgil himself would normally reside, he also meets several poets here, Homer, Horace, Ovid and Lucan, which along with Virgil count them as 6 in the number of great poets (how humble of Dante), in this layer many famous Trojans are found here such as Hector and Aeneas (I sadly do not have the time to go into detail over who they were), and Julius Caesar is also here. He later meets famous philosphers such as Plato, Socrates and Aristotle, Limbo is where all the virtious damned go, however there are a few exceptions with a few non-christians find their way to Purgatory and Heaven. It is also stated by Virgil that once 'a Might One' (presumably Jesus) came down here and took several biblical figures (Noah, Abel, Abraham, Moses, etc.) to forgive them and brought them to Heaven.", orders=[["Incorrect","Correct", "Incorrect", "Incorrect"], ["Incorrect", "Incorrect", "Correct", "Incorrect"]], answers=[["7", "6", "4", "5"], ["Aristotle","Plato","Epicurus","Socrates"]], Questions=["How many 'Great poets' were counted?", "Which of these philosphers was not explicitly mentioned to be in Limbo?"], title="Circle 1, Limbo", 
                                                                                                                            command=lambda: layer(texts=["It is in this layer Dante meets figures such as Achilles, Helen and Paris (of Troy), Cleopatra and many others, all of whom were known to have done things for sexual love within in their lifetimes, there were notably many rulers here, the canto was nicknamed the canto of queens.", "There is a long section dedicated to the story of Francesca da Rimini, who married Giovanni Malatesta for political purposes but fell in love with his younger brother, Paolo Malatesta, in the end Giovanni stabbed both to the death."], images=["2.jpg", "affair.jpg"], bg="#1B1D2A", fg='#FFFFFF', intro_text="This is the 2nd circle of Hell, now the punishments truly begin, here you will meet Minos, judge of the dead, he judges the souls by making them confess for their sins, and this alone is how they are judged, Dante avoids judgement with Virgil stopping Minos, The lustful are punished here, being constantly thrown around by violent winds.", orders=[["Incorrect","Correct", "Incorrect", "Incorrect"], ["Correct", "Incorrect", "Incorrect", "Incorrect"]], answers=[["The canto of kings", "The canto of queens", "The canto of royalty", "The royal canto"], ["Giovanni Malatesta","Paolo Malatesta","She didn't cheat","She never married"]], Questions=["What is Canto V (the canto dedicated to this layer) nicknamed?", "Who did Francesca da Rimini cheat with?"], title="Circle 2, Lust",
                                                                                                                             command=lambda: layer(["Cerberus.jpg", "3.jpg"], ["The gluttonous are simply given what they deserve, the circle of Hell exposes the true nature of gluttony, not just of desire for food and drink, but the overall addiction.", "In this circle Dante meets a Florentine, named Ciacco (meaning 'hog'), Ciacco gives a political prophecy claiming that the black guelphs would throw out the white (Dante's side), which indeed happened with aid from Pope Boniface VIII"], bg="#745E3F", fg='#FFFFFF', intro_text="This is 3rd circle of Hell, here the gluttonous are punished, Cerberus forever eats the gluttons whilst icy rain pours down on them, creating a putrid slush, Dante uses the slush to get past Cerberus", orders=[["Incorrect","Incorrect", "Incorrect", "Correct"], ["Incorrect", "Incorrect", "Correct", "Incorrect"]], answers=[["A bone", "A random damned soul", "Meat", "Mud"], ["He exiled ", "Pope Boniface VII", "Pope Boniface VIII", "Pope Boniface IX"]], Questions= ["What does Dante use to stop Cerberus?", "Who helped aid the event that caused Dante's exile from Florence?"], title="Circle 3, Gluttony",
                                                                                                                              command=lambda: layer(["Plutus.jpg", "4.jpg"], ["Pape Satàn, pape Satàn aleppe", "It is here all those that suffered from greed are punished, weighed down by large amounts of wealth, burdened truly, almost pitiful, it does not matter whether money was spent as if it were water, or if it were hoarded, it is greed nevertheless."], bg="#98754B", fg='#FFFFFF', intro_text="This is 4th circle of Hell, here the avarcious and the spendthrifts are punished. They are weighed down by bags containing great wealth, their greed stopping them, Dante and Virgil also encounter Plutus here, a version of the roman God of wealth.", orders=[["Incorrect","Correct", "Incorrect", "Incorrect"], ["Incorrect", "Correct", "Incorrect", "Incorrect"]], answers=[["Pape Satan, pape Satan aleppe", "Pape Satàn, pape Satàn aleppe", "Pape Sàtan, pape Sàtan aleppe", "Pape Sàtàn, pape Sàtàn aleppe"], ["Bags of money", "Bags of wealth", "Bags of stone", "Stone"]], Questions= ["What is said by Plutus?", "What weighs down the sinners?"], title="Circle 4, Greed", 
                                                                                                                               command=lambda: layer(["8.jpg", "Dis.jpg"], ["They approach the city of Dis, a city guarded by fallen angels, Virgil is unable to convince them to allow passage.", "Dante and Virgil and threatened by the furies and Medusa, but an angel sent from heaven allows them passage into the city, bringing them to the deeper layers of Hell."], bg="#4D4742", fg='#FFFFFF', intro_text="This is 5th circle of Hell, don't we all love the River Styx? Here the wrathful fight each other on the surface, while the sullen (passively wrathful) lay under the river, sunken.", orders=[["Correct","Incorrect", "Incorrect", "Incorrect"], ["Incorrect", "Incorrect", "Incorrect", "Correct"]], answers=[["Fallen Angels", "Demons", "The Furies", "Medusa"], ["They never make it through","It was already open","Virgil reasons with the fallen angels","An angel opens the gate"]], Questions=["Who guarded the city of Dis?", "How did they pass through the gate?"], title="Circle 5, Wrath",
                                                                                                                                command=lambda: layer(["6.jpg", "6_2.jpg"], ["It is mentioned that the dead can see the future, however this portal to the future is closed", "This circle of Hell allows for an easy view of all the deeper layers, with each ring of the subsequent layer visible."], bg="#494949", fg='#FFFFFF', intro_text="This is 6th circle of Hell, here lies the heretics, remember Epicurus in one of the previous questions? He's here, he believed the soul died with the body, but in Inferno there is plain heresy, hence he is here.", orders=[["Incorrect","Correct", "Incorrect", "Incorrect"], ["Incorrect", "Incorrect", "Correct", "Incorrect"]], answers=[["They never could", "The 'portal' to the future is closed", "They can still see it, the portal is still open.", "They still can, it is an innate ability"], ["Aristotle", "Socrates", "Epicurus", "Plato"]], Questions=["Why can the dead no longer see the future?", "Which philospher and his followers were damned to this circle of Hell?"], title= "Circle 6, Heresy",
                                                                                                                                 command=lambda: layer(["7_1.jpg", "7_1_2.jpg"], ["Water is refreshing is it not? Well, the Phlegethon contains firey water... in it conquerers like Alexander the Great can be found.", "Centaurs shoot the sinners back into the water if they ever rise too high, their leaders are Chiron and Pholus, and Nessus guides the poets."], bg="#2B0A05", fg='#FFFFFF', intro_text="Welcome, you have come far travellar, this is the 1st ring of Hell of the 7th circle, the layer of Malice, containing the punishments of those whose who have commited sins of violence and inhumanity. The first ring contains those who bring violence upon others or their property.", orders=[["Correct","Incorrect", "Incorrect", "Incorrect"], ["Correct", "Incorrect", "Incorrect", "Incorrect"]], answers=[["Phlegethon", "Acheron", "Styx", "Lethe"], ["Centuars", "Minotaurs", "Harpies", "Demons"]], Questions=["Which river are the damned kept in?", "What mythological species shoots down the sinners who go too high?"], title="Circle 7, Ring 1", 
                                                                                                                                  command=lambda: layer(["7_2.jpg", "7_2_2.jpg"], ["The souls who damned themselves are nothing but thorny trees now, this is no paradise, only damnation awaits thou. Thou may only speak when harmed. They shall not recieve their bodies back when the final judgement comes, they have wasted them already.", "The harpies perch upon them, feeding upon them."], bg="#707070", fg='#FFFFFF', intro_text="This is the 2nd ring of the 7th circle, here lies those who have commited violence against themself or their property. You cannot take the easy way to Paradise.", orders=[["Incorrect","Correct", "Incorrect", "Incorrect"], ["Incorrect", "Incorrect", "Incorrect", "Correct"]], answers=[["They retain their bodies in Hell", "They become a thorny tree for the rest of time", "They recieve their bodies back post-final judgement", "They lose their bodies after the final judgement"], ["Centaurs", "Birds", "Crows", "Harpies"]], Questions=["What happens to the bodies of those who damn thyselves?", "Which mythological species feeds upon the trees?"], title="Circle 7, Ring 2", 
                                                                                                                                   command=lambda: layer(["Desert.jpg", "Geryon.jpg"], ["The desert exists due to the overflowing of the Phlegethon, which flows through ring 2 down here, creating the burning desert.", "Upon a cliff, a waterfull plunges down to the next layer, the way down is by the beast Geryon, Monster of Fraud"], bg="#938676", fg='#FFFFFF', intro_text="The 3rd and last ring of the 7th circle of Hell, here you find those who dared to hurt God and Nature, they deserved no lesser of a fate. Blasphemers, Sodomites and Usurers, all unnatural, left in the sterile desert.", orders=[["Incorrect","Correct", "Incorrect", "Incorrect"], ["Correct", "Incorrect", "Incorrect", "Incorrect"]], answers=[["Lethe", "Phlegthon", "Acheron", "Styx"], ["Fraud", "Greed", "Violence", "Wrath"]], Questions=["The overflow of which river causes the desert?", "Geryon is the monster of what?"], title="Circle 7, Ring 3",
                                                                                                                                    command=lambda: layer(["Bolgia.jpg", "Well.jpg"], ["Panderers and seducers are whipped by horned demons for all eternity, flatterers are covered in excrement, simoniacs are placed head down in rock with flames burning their feet, sorcerers (and other 'false prophets') have their head twisted around on their body, barrators are immersed in boiling tar, hypocrites are made to walk for eternity in leaden robes, theives are continuously attacked by reptiles, fraudulent advisors are burnt in flame, notably Ulysses (Odysseus) is in there, where he recounts the tale of his final voyage, having seen Purgatory himself, and being punished for such. Sowers of discord and hacked for all eternity by a demon, and finally falsifiers are eternally cursed with varying diseases.", "The Central Well of Malebolge is the entrance to the final layer, and surrounded by biblical giants and greek giants who are damned to forever guard it."], bg="#826A3C", fg='#FFFFFF', intro_text="You have ventured very far traveller, to the 8th circle of Hell, here you shall find those who have commited sins of deceit against those who have no cause of trust. The pimps and seducers, the flatterers, the simonists, the soothsayers, the corrupt officials, the hypocrites, the theieves, the intellectually dishonest, the rabble-rousers and the counterfeiters, all in their own smaller boliga (all in one place cause I'm lazy, and I'm lacking time).", orders=[["Incorrect","Correct", "Incorrect", "Incorrect"], ["Incorrect", "Incorrect", "Correct", "Incorrect"]], answers=[["Paradise", "Purgatory", "Hell", "Ogygia"], ["Titans", "Demons", "Giants", "Fallen Angels"]], Questions = ["What did Ulysses/Odysseus see that caused his death?", "Who defends the Central Well of Malebolge?"], title="Circle 8, Fraud", 
                                                                                                                                     command=lambda: layer(["9.jpg"], ["It is nothing but ice, the traitorous souls trapped within it, it begins with Caina, named after Cain, the man who commited the first murder, here lies those that kill their family, their necks and heads are above the ice, Antenora named after Antenor who betrayed Troy as a trojan, this is where traitors to their country lie, their heads are above the ice, but they cannot move it, Ptolomaea, named Ptolemy who broke the laws of xenia, betraying guests, they are denied even the right to cry, and last there is Judecca, named after the 2nd greatest betrayer, Judas, containing traitors against Lords and Benefactors, they are completely covered in ice unable to speak nor move."], bg="#3C4FB2", fg='#FFFFFF', intro_text="Your journey approaches its end traveller, this is the 9th and final circle of Hell, containing all of those who have commited sins of deceit against those who have cause to trust, those who have dared to decieve their family, their nation, benefactors and have dared to defy xenia, you approach the centre, if you truly wish to see those who have commited the most foul sins. To see the ultimate traitor.", orders=["Incorrect","Correct", "Incorrect", "Incorrect"], answers=["Judas", "Dis", "Cain", "Ptolemy"], Questions=["Who does not have a layer of the 9th circle named after them?"], title="Circle 9, Treachery",
                                                                                                                                      command=lambda: layer(["Lucifer.jpg"], ["Lucifer"], bg="#300900", fg='#9a1d00', intro_text="...", orders=[["Correct","Correct", "Correct", "Correct"]], answers=[["Lucifer", "Satan", "The Devil", "Beelzebub"]], Questions=["Who is he?"], title="...", command=lambda: root.destroy() ))))))))))))))).pack()
Label(canvas, text="LEAVE", bg='#300900', fg='#400900', font=('wingdings', 10)).pack()
if __name__ == "__main__":
  root.mainloop()