from tkinter import *
from PIL import Image, ImageTk
def main(root):
  root.destroy()
  root = Tk()
  root.configure(bg='#300900')
  root.config(width=500, height=500)
  root.title("Layer 1")
  root.maxsize(2000,2000)
  root.minsize(500,500)
  root.geometry("500x500")
  ico = Image.open('test.jpg')
  photo = ImageTk.PhotoImage(ico)
  root.wm_iconphoto(False, photo)
  Label(text="Just remember... you did this to yourself - ", bg='#300900', fg='#9a1d00', font=('Public Sans',20)).place(relx=0.32, rely=0)
  text = Label(text="Dante", bg='#300900', fg='#9a1d00', font=('Edwardian Script ITC',20))
  text.place(relx=0.6, rely=0.005)
  image = Image.open('placeholder.png')
  new_size = (image.width // 2, image.height // 2)  # Example: Shrink by half
  image = image.resize(new_size)
  image = ImageTk.PhotoImage(image)
  Label(image=image, padx=0.1, pady=0.1).place(relx=0.35, rely=0.1)
  text = Text(bg='#300900', fg='#9a1d00')
  text.insert(END, '''Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec urna lacinia, dignissim sapien eget, interdum nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce non euismod odio, sed vehicula velit. Mauris vitae nulla auctor, euismod nibh vel, ullamcorper ipsum. Fusce aliquet ipsum at est consectetur porta. Curabitur erat mauris, tempor vel pretium nec, molestie sit amet nibh. Aliquam scelerisque gravida diam id porttitor. Vestibulum sit amet sodales purus, sed tincidunt massa. Vestibulum imperdiet dapibus tellus et accumsan. Pellentesque congue nulla a dolor blandit congue sit amet nec sapien. Ut molestie nulla eget nibh fermentum volutpat. Cras libero elit, dapibus non felis vel, molestie porttitor arcu. Morbi pretium diam mauris, in lobortis nulla aliquam blandit. Donec tempor hendrerit libero ullamcorper sodales.
In non lorem porttitor, euismod nulla quis, ultrices sem. Nunc volutpat elit quis urna porttitor gravida. Morbi auctor vestibulum ultricies. Etiam in quam tincidunt, hendrerit enim in, pretium nunc. Nulla imperdiet ex vel porta consectetur. Vestibulum aliquam libero ac nisl facilisis malesuada. Etiam a facilisis ligula.
Donec vitae pellentesque felis. Integer pharetra enim quis purus viverra, congue accumsan nisl molestie. Curabitur sed lacus nibh. Ut egestas urna et dui volutpat, in molestie massa congue. Nam at sem ante. Suspendisse potenti. Praesent congue, felis sit amet cursus viverra, elit tellus facilisis elit, sed hendrerit leo nibh vel neque. Fusce eu turpis ut neque porta ullamcorper sit amet eu tellus. Vivamus lorem odio, ultrices ut ante at, posuere placerat diam. Cras pulvinar lorem non odio mollis, id accumsan lacus ornare. In laoreet aliquet tortor nec bibendum. In vel ligula nibh. Vestibulum semper lorem sed magna mattis, volutpat accumsan nunc cursus. Suspendisse semper pharetra semper. Nulla gravida faucibus nisl, eu laoreet odio porta id.
Sed consequat, velit ut finibus tincidunt, magna lorem congue nulla, vel elementum ex augue vel mauris. Vestibulum ornare mi enim. In volutpat odio lacus, vel iaculis tortor tincidunt nec. Sed hendrerit fermentum purus non tristique. Sed feugiat scelerisque finibus. Fusce porta tristique mattis. Phasellus ullamcorper nisi at vehicula auctor. Cras maximus ultrices purus, et mollis enim finibus id. Aenean gravida, orci ut ultrices dictum, purus diam elementum dolor, id hendrerit lorem felis vel dolor. Sed aliquam tellus urna, et lacinia dui pretium luctus. Nulla pharetra est nunc, vitae consequat orci faucibus sit amet. Vivamus in orci et ligula molestie ornare vel vel enim. Aliquam nisl lectus, condimentum id ultrices eget, ullamcorper a ante.
Nam congue fermentum elit ut interdum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nullam ac eros suscipit, interdum enim nec, facilisis massa. Proin iaculis magna sed nisi fermentum rhoncus. Quisque pulvinar sem quam, ut sollicitudin dolor hendrerit non. Donec non pellentesque ante. Morbi vel feugiat massa. Quisque vestibulum tortor ut risus malesuada, non posuere dui posuere. Nunc molestie sed ipsum at dignissim. Donec vel lobortis arcu. Integer eget tellus in quam dictum volutpat. Donec ullamcorper, turpis luctus aliquam sodales, felis nunc rhoncus turpis, sit amet accumsan tellus magna rhoncus purus. Quisque sit amet convallis lectus, ut sodales erat. Nullam commodo urna lectus, nec dictum libero dictum non. Aliquam erat volutpat.''')
  text.place(relx=0.35, rely=0.6)
  scrollbar = Scrollbar(root)
  scrollbar.pack(side=RIGHT, fill=Y)
  scrollbar.config(command= text.yview)
  text.config(yscrollcommand= scrollbar.set)
  root.mainloop()
root = Tk()
root.configure(bg='#300900')
root.title("Heck*")
root.maxsize(2000,2000)
root.minsize(500,500)
root.geometry("500x500+120+60")
ico = Image.open('test.jpg')
photo = ImageTk.PhotoImage(ico)
root.wm_iconphoto(False, photo)
Label(text="Welcome to the world of Dante's Inferno" ,bg='#300900', fg='#9a1d00', font=('Terminal', 50)).pack()
Label(text="\n \n \n \n \n \n \n \n",bg='#300900', fg='#9a1d00').pack()
Button(text="Join the souls of the damned", bg='#300900', fg='#9a1d00' ,font=('Symbol', 15), command=lambda: main(root)).pack()
Label(text="LEAVE", bg='#300900', fg='#400900', font=('wingdings', 10)).pack()
root.mainloop()